services:
  nginx:
    build:
      context: ./server

  triton:
    build: 
      context: ./triton
    container_name: triton_server
    environment:
      - MODEL_REPOSITORY=/app/model_repository  # Ensure this matches your Docker setup
    ports:
      - "8000:8000"  # HTTP service
      - "8001:8001"  # gRPC service
      - "8002:8002"  # Metrics service
    volumes:
      - ./triton/model_repository:/app/model_repository # Map local model repository to the one in the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
