networks:
  default:
    driver: bridge

volumes:
  model-data:

services:
  nginx:
    image: nginx:alpine
    build:
      context: ./react-frontend
    ports:
      - "80:80"
    restart: unless-stopped

  flask:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - TRITON_SERVER_URL=http://triton:8000
    volumes:
      - model-data:/app/triton/model_repository
    restart: unless-stopped

  triton:
    build: 
      context: ./triton
    container_name: triton_server
    environment:
      - MODEL_REPOSITORY=/app/model_repository
    ports:
      - "8000:8000"  # HTTP service
      - "8001:8001"  # gRPC service
      - "8002:8002"  # Metrics service
    volumes:
      - model-data:/app/model_repository
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
